# Generated by Django 4.2 on 2023-04-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='cat',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='vistas',
            field=models.IntegerField(default=0),
        ),
    ]
