# Generated by Django 4.2 on 2023-05-01 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_cat_articles_likes_articles_vistas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='cat',
            new_name='categoria',
        ),
    ]
